In [20]:
import os
import pandas as pd

folder_path = '/Users/will/Documents/Beacon MVP/Projects/IESO Data Set Up/output_data'
temp_folder = '/Users/will/Documents/Beacon MVP/Projects/IESO Data Set Up/temp_files/'
output_folder = '/Users/will/Documents/Beacon MVP/Projects/IESO Data Set Up/output_data'

In [37]:
df = pd.read_csv(os.path.join(temp_folder +'grouped_weather_data_unclean.csv'))

/var/folders/06/r1b4q53n1z9c4xqz_6bqq9zc0000gn/T/ipykernel_32864/260928070.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(temp_folder +'grouped_weather_data_unclean.csv'))

In [10]:
df.head()

    Date/Time (LST) Climate ID  Temp (°C)
0  2023-01-01 00:00    6117700        1.1
1  2023-01-01 01:00    6117700        0.7
2  2023-01-01 02:00    6117700        0.8
3  2023-01-01 03:00    6117700        0.3
4  2023-01-01 04:00    6117700        0.2

# Linear interpolation

In [12]:
df.columns

Index(['Date/Time (LST)', 'Climate ID', 'Temp (°C)'], dtype='object')

In [13]:
df['Temp (°C)'] = df['Temp (°C)'].interpolate(method='linear', limit_direction='both')

In [17]:
nan_count = df['Temp (°C)'].isna().sum()
print(f"NaN count in 'Temp (C)': {nan_count}")

NaN count in 'Temp (C)': 0

In [22]:
nan_count = df['Climate ID'].isna().sum()
print(f"NaN count in Climate ID': {nan_count}")

NaN count in Climate ID': 0

# Export

In [25]:
df.head()

    Date/Time (LST) Climate ID  Temp (°C)
0  2023-01-01 00:00    6117700        1.1
1  2023-01-01 01:00    6117700        0.7
2  2023-01-01 02:00    6117700        0.8
3  2023-01-01 03:00    6117700        0.3
4  2023-01-01 04:00    6117700        0.2

In [33]:
# later on other script facing import issues based on inconsistent Dtypes and then special degree character... addressing here
df['Climate ID'] = df['Climate ID'].astype(str)
df = df.rename(columns={'Temp (°C)':'Temp (C)'})

In [34]:
df

         Date/Time (LST) Climate ID  Temp (C)
0       2023-01-01 00:00    6117700       1.1
1       2023-01-01 01:00    6117700       0.7
2       2023-01-01 02:00    6117700       0.8
3       2023-01-01 03:00    6117700       0.3
4       2023-01-01 04:00    6117700       0.2
...                  ...        ...       ...
894739  2024-12-31 19:00    6068145      -0.5
894740  2024-12-31 20:00    6068145      -0.3
894741  2024-12-31 21:00    6068145      -0.6
894742  2024-12-31 22:00    6068145      -0.6
894743  2024-12-31 23:00    6068145      -0.7

[894744 rows x 3 columns]

In [36]:
df.to_csv(os.path.join(temp_folder+'weather_data_clean.csv'),index=False)